[{"TimeUTC":"2024-12-02 09:25:43","timestampInMs":1733131543575,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::lsbjx-1733131542524-afb8cf2d25b0","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:42","timestampInMs":1733131542559,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::lsbjx-1733131542524-afb8cf2d25b0","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":996,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:40","timestampInMs":1733131540476,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::kzrbp-1733131539450-f590814e7c34","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:39","timestampInMs":1733131539492,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::kzrbp-1733131539450-f590814e7c34","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":968,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:38","timestampInMs":1733131538379,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::6gwmc-1733131537335-3a7325d244e4","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:37","timestampInMs":1733131537377,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::6gwmc-1733131537335-3a7325d244e4","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":980,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:37","timestampInMs":1733131537294,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::qvxss-1733131536258-7505a4424d04","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:36","timestampInMs":1733131536292,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::qvxss-1733131536258-7505a4424d04","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":985,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:34","timestampInMs":1733131534176,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::6vccx-1733131533130-2a79ccf6c580","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:33","timestampInMs":1733131533169,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::6vccx-1733131533130-2a79ccf6c580","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":992,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:32","timestampInMs":1733131532035,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::477km-1733131530997-defb10be2757","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:31","timestampInMs":1733131531033,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::477km-1733131530997-defb10be2757","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":987,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:30","timestampInMs":1733131530791,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::tp7jr-1733131529750-79926e05321a","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:29","timestampInMs":1733131529791,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::tp7jr-1733131529750-79926e05321a","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":984,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:28","timestampInMs":1733131528656,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::555pm-1733131527612-b506cdaad35a","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:27","timestampInMs":1733131527655,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::555pm-1733131527612-b506cdaad35a","requestUserAgent":["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":985,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:13","timestampInMs":1733131513256,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::9wsf9-1733131512212-10458ebcdb13","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:12","timestampInMs":1733131512660,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::rcr5g-1733131511567-5d7055036893","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:12","timestampInMs":1733131512422,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::6qj8h-1733131511323-7947a6815df6","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:12","timestampInMs":1733131512247,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::9wsf9-1733131512212-10458ebcdb13","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":995,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:11","timestampInMs":1733131511602,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::rcr5g-1733131511567-5d7055036893","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1042,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:11","timestampInMs":1733131511358,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::6qj8h-1733131511323-7947a6815df6","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1048,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:10","timestampInMs":1733131510905,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::75rzg-1733131509802-6a6ed72d1ad5","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:10","timestampInMs":1733131510115,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::kzrbp-1733131509030-259dfe5e4cc2","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:09","timestampInMs":1733131509859,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::75rzg-1733131509802-6a6ed72d1ad5","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1030,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:09","timestampInMs":1733131509520,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::qwmrf-1733131508419-2c95dc2ebd9e","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:09","timestampInMs":1733131509075,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::kzrbp-1733131509030-259dfe5e4cc2","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1024,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:08","timestampInMs":1733131508794,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::2b6rw-1733131507694-6adbee1065cd","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:08","timestampInMs":1733131508455,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::qwmrf-1733131508419-2c95dc2ebd9e","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1042,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:07","timestampInMs":1733131507731,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::2b6rw-1733131507694-6adbee1065cd","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1048,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:07","timestampInMs":1733131507517,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::c28z5-1733131505417-0a4f0cc6ad15","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:07","timestampInMs":1733131507465,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::mt9fs-1733131505357-47f27a884a4e","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:07","timestampInMs":1733131507377,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::9tw89-1733131505387-9675a864881a","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:05","timestampInMs":1733131505592,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::c28z5-1733131505417-0a4f0cc6ad15","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1061,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:05","timestampInMs":1733131505591,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::mt9fs-1733131505357-47f27a884a4e","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":1019,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:25:05","timestampInMs":1733131505591,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::9tw89-1733131505387-9675a864881a","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":984,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:35:58","timestampInMs":1733132158833,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sin1::iad1::99w6f-1733132157644-41a1f2400175","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:35:57","timestampInMs":1733132157763,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sin1::iad1::99w6f-1733132157644-41a1f2400175","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1052,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:35:55","timestampInMs":1733132155714,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sin1:sin1::iad1::4t8vc-1733132154219-810a29e04322","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:35:54","timestampInMs":1733132154649,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sin1:sin1::iad1::4t8vc-1733132154219-810a29e04322","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1046,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:36:01","timestampInMs":1733132161159,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sin1:sin1:sfo1:sfo1:sfo1::iad1::h7mdf-1733132160055-b7e8639b7b0f","requestUserAgent":["Vercel Edge Functions"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:36:00","timestampInMs":1733132160095,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sin1:sin1:sfo1:sfo1:sfo1::iad1::h7mdf-1733132160055-b7e8639b7b0f","requestUserAgent":["Vercel Edge Functions"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1047,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:35:02","timestampInMs":1733132102937,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::4ccds-1733132101819-62d60d29d08d","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:35:01","timestampInMs":1733132101867,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::4ccds-1733132101819-62d60d29d08d","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1053,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:59","timestampInMs":1733132099743,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::7nrwf-1733132098628-91c22b2542ca","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:58","timestampInMs":1733132098666,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::7nrwf-1733132098628-91c22b2542ca","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1058,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:57","timestampInMs":1733132097517,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::x72pm-1733132096358-9adeffa2a970","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:56","timestampInMs":1733132096404,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.png","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::x72pm-1733132096358-9adeffa2a970","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1095,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:56","timestampInMs":1733132096314,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::v4dtj-1733132095156-2adfc1f60806","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:55","timestampInMs":1733132095198,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::v4dtj-1733132095156-2adfc1f60806","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1100,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:53","timestampInMs":1733132093038,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::pl8hp-1733132091870-cd5e26c86271","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:51","timestampInMs":1733132091909,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::pl8hp-1733132091870-cd5e26c86271","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1110,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:50","timestampInMs":1733132090738,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::tks8x-1733132089621-03f5aad33986","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:49","timestampInMs":1733132089660,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::tks8x-1733132089621-03f5aad33986","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1063,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:49","timestampInMs":1733132089434,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::gb2bm-1733132088301-e58ee765e053","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:48","timestampInMs":1733132088335,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::gb2bm-1733132088301-e58ee765e053","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1065,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:47","timestampInMs":1733132087243,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::tks8x-1733132086134-c42f799ca36b","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:46","timestampInMs":1733132086178,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::tks8x-1733132086134-c42f799ca36b","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 OPR/112.0.0.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1050,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:32","timestampInMs":1733132072954,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::lb64z-1733132071865-9b449e23d0dd","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:32","timestampInMs":1733132072766,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::25sg8-1733132071726-21cd8e0e7aff","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:31","timestampInMs":1733132071901,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::lb64z-1733132071865-9b449e23d0dd","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1035,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:31","timestampInMs":1733132071771,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::25sg8-1733132071726-21cd8e0e7aff","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":977,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:29","timestampInMs":1733132069738,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::hx42m-1733132068696-3d7149e7f70c","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:29","timestampInMs":1733132069595,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::rkh6v-1733132068482-9d10c59bba6e","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:29","timestampInMs":1733132069147,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::gb2bm-1733132068093-8e8f7d407191","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:29","timestampInMs":1733132069003,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::67bvp-1733132067913-97e78a10b2c3","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:28","timestampInMs":1733132068740,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::hx42m-1733132068696-3d7149e7f70c","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":977,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:28","timestampInMs":1733132068520,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::rkh6v-1733132068482-9d10c59bba6e","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1059,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:28","timestampInMs":1733132068130,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::gb2bm-1733132068093-8e8f7d407191","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1003,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:27","timestampInMs":1733132067948,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::67bvp-1733132067913-97e78a10b2c3","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1031,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:27","timestampInMs":1733132067711,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::h7mdf-1733132065512-7f1039ddc029","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:27","timestampInMs":1733132067588,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::hx42m-1733132065560-801402d83201","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:27","timestampInMs":1733132067564,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::48xll-1733132065542-45055971cdd1","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:27","timestampInMs":1733132067421,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sfo1::iad1::x72pm-1733132065549-3e0b33822264","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.\nTraceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:25","timestampInMs":1733132065731,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::x72pm-1733132065549-3e0b33822264","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":969,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:25","timestampInMs":1733132065731,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::hx42m-1733132065560-801402d83201","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1032,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:25","timestampInMs":1733132065730,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::h7mdf-1733132065512-7f1039ddc029","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1029,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:34:25","timestampInMs":1733132065730,"requestPath":"ytdown-k67omxmov-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sfo1::iad1::48xll-1733132065542-45055971cdd1","requestUserAgent":["vercel-screenshot/1.0"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-k67omxmov-pindl.vercel.app","deploymentDomain":"ytdown-k67omxmov-pindl.vercel.app","deploymentId":"dpl_BU5mouUTokXU4d6HpMKPUzDTJbfy","lambdaDurationInMs":1024,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:26:31","timestampInMs":1733131591619,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sin1:sin1:sfo1:sfo1:sfo1::iad1::lv65z-1733131590568-84a8084671b8","requestUserAgent":["Vercel Edge Functions"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:26:30","timestampInMs":1733131590610,"requestPath":"ytdown-mg3c9rzpp-pindl.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sin1:sin1:sfo1:sfo1:sfo1::iad1::lv65z-1733131590568-84a8084671b8","requestUserAgent":["Vercel Edge Functions"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentDomain":"ytdown-mg3c9rzpp-pindl.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":995,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:26:29","timestampInMs":1733131589993,"requestPath":"ytdown-sage.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":-10,"requestId":"sin1::iad1::9mntm-1733131588843-64b757211797","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-sage.vercel.app","deploymentDomain":"ytdown-sage.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:26:28","timestampInMs":1733131588983,"requestPath":"ytdown-sage.vercel.app/favicon.ico","requestMethod":"GET","responseStatusCode":500,"requestId":"sin1::iad1::9mntm-1733131588843-64b757211797","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-sage.vercel.app","deploymentDomain":"ytdown-sage.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":992,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:26:25","timestampInMs":1733131585095,"requestPath":"ytdown-sage.vercel.app/","requestMethod":"GET","responseStatusCode":-10,"requestId":"sin1:sin1::iad1::jm6qf-1733131583626-b074930bdcd2","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-sage.vercel.app","deploymentDomain":"ytdown-sage.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":-1,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":-1,"lambdaMemorySize":-1,"message":"Traceback (most recent call last):\nFile \"/var/task/vc__handler__python.py\", line 14, in <module>\n__vc_spec.loader.exec_module(__vc_module)\nFile \"<frozen importlib._bootstrap_external>\", line 995, in exec_module\nFile \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\nFile \"/var/task/script/app.py\", line 1, in <module>\nfrom flask import Flask, render_template, request, send_file, Response, redirect, url_for\nFile \"/var/task/flask/__init__.py\", line 7, in <module>\nfrom .app import Flask as Flask\nFile \"/var/task/flask/app.py\", line 28, in <module>\nfrom . import cli\nFile \"/var/task/flask/cli.py\", line 18, in <module>\nfrom .helpers import get_debug_flag\nFile \"/var/task/flask/helpers.py\", line 16, in <module>\nfrom werkzeug.urls import url_quote\nImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py). Did you mean: 'unquote'?\nPython process exited with exit status: 1. The logs above can help with debugging the issue.","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"},{"TimeUTC":"2024-12-02 09:26:24","timestampInMs":1733131584084,"requestPath":"ytdown-sage.vercel.app/","requestMethod":"GET","responseStatusCode":500,"requestId":"sin1:sin1::iad1::jm6qf-1733131583626-b074930bdcd2","requestUserAgent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"],"level":"error","environment":"production","branch":"main","vercelCache":"MISS","type":"lambda","function":"/script/app.py","host":"ytdown-sage.vercel.app","deploymentDomain":"ytdown-sage.vercel.app","deploymentId":"dpl_5LKUdZcT8anfcBTirB7NKByQsdYU","lambdaDurationInMs":995,"lambdaRegion":"iad1","lambdaMaxMemoryUsed":62,"lambdaMemorySize":1024,"message":"","projectId":"prj_rSrQWQ5tugQePuGirjdbKrZ4eTvJ","wafAction":"-"}]